apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l5gwsvash-nodejs 
  janus-idp.io/tekton: l5gwsvash-nodejs
  backstage.io/kubernetes-id: l5gwsvash-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l5gwsvash-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  